import { InsertPark } from "@shared/schema";

export const nationalParks: InsertPark[] = [
  {
    name: "Acadia",
    description: "Acadia National Park protects the natural beauty of the highest rocky headlands along the Atlantic coastline, an abundance of habitats, and a rich cultural heritage.",
    state: "Maine",
    imageUrl: "https://images.unsplash.com/photo-1601924582970-9238bcb495d9?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=500",
    icon: "fas fa-mountain",
    established: "1919",
  },
  {
    name: "Arches",
    description: "Discover a landscape of contrasting colors, landforms, and textures unlike any other. The park has over 2,000 natural stone arches, hundreds of soaring pinnacles, massive rock fins, and giant balanced rocks.",
    state: "Utah",
    imageUrl: "https://images.unsplash.com/photo-1602088693770-4e8fb229f413?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=500",
    icon: "fas fa-archway",
    established: "1971",
  },
  {
    name: "Badlands",
    description: "The rugged beauty of the Badlands draws visitors from around the world. These striking geologic deposits contain one of the world's richest fossil beds, preserving ancient mammals such as the rhino, horse, and saber-toothed cat.",
    state: "South Dakota",
    imageUrl: "https://images.unsplash.com/photo-1502329043111-32736f45789d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=500",
    icon: "fas fa-mountain",
    established: "1978",
  },
  {
    name: "Big Bend",
    description: "Big Bend National Park features massive canyons, vast desert expanses, and the entire Chisos mountain range. Here, you can explore one of the last remaining wild corners of the United States.",
    state: "Texas",
    imageUrl: "https://images.unsplash.com/photo-1623156144941-d196f6423035?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=500",
    icon: "fas fa-mountain",
    established: "1944",
  },
  {
    name: "Bryce Canyon",
    description: "Bryce Canyon National Park is known for crimson-colored hoodoos, which are spire-shaped rock formations, carved over thousands of years.",
    state: "Utah",
    imageUrl: "https://images.unsplash.com/photo-1551649001-7a2482d98d05?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=500",
    icon: "fas fa-mountain",
    established: "1928",
  },
  {
    name: "Canyonlands",
    description: "Canyonlands invites you to explore a wilderness of canyons and buttes carved by the Colorado River and its tributaries. Rivers divide the park into four districts: Island in the Sky, The Needles, The Maze, and the rivers themselves.",
    state: "Utah",
    imageUrl: "https://images.unsplash.com/photo-1559665881-6b9f74304f9e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=500",
    icon: "fas fa-mountain",
    established: "1964",
  },
  {
    name: "Capitol Reef",
    description: "Capitol Reef National Park is a hidden treasure filled with cliffs, canyons, domes, and bridges in the Waterpocket Fold, a geologic monocline (a wrinkle on the earth) extending almost 100 miles.",
    state: "Utah",
    imageUrl: "https://images.unsplash.com/photo-1590562148789-461be3fc9aca?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=500",
    icon: "fas fa-mountain",
    established: "1971",
  },
  {
    name: "Carlsbad Caverns",
    description: "High ancient sea ledges, deep rocky canyons, flowering cactus, and desert wildlife—treasures above the ground in the Chihuahuan Desert. Below the surface are more than 119 caves formed when sulfuric acid dissolved limestone, creating magnificent chambers.",
    state: "New Mexico",
    imageUrl: "https://images.unsplash.com/photo-1566766811754-82ce686d6543?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=500",
    icon: "fas fa-cave",
    established: "1930",
  },
  {
    name: "Channel Islands",
    description: "Channel Islands National Park encompasses five remarkable islands and their ocean environment, preserving and protecting a wealth of natural and cultural resources. Isolation over thousands of years has created unique animals, plants, and archeological resources found nowhere else on Earth.",
    state: "California",
    imageUrl: "https://images.unsplash.com/photo-1559244673-9cee3ac2bf25?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=500",
    icon: "fas fa-island-tropical",
    established: "1980",
  },
  {
    name: "Crater Lake",
    description: "Crater Lake inspires awe. Native Americans witnessed its formation 7,700 years ago, when a violent eruption triggered the collapse of a tall peak. Scientists marvel at its purity: fed by rain and snow, it's the deepest lake in the USA and perhaps the most pristine on earth.",
    state: "Oregon",
    imageUrl: "https://images.unsplash.com/photo-1486068338746-bc8c63a5a918?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=500",
    icon: "fas fa-water",
    established: "1902",
  },
  {
    name: "Death Valley",
    description: "In this below-sea-level basin, steady drought and record summer heat make Death Valley a land of extremes. Yet, each extreme has a striking contrast. Despite its morbid name, a great diversity of life survives in Death Valley.",
    state: "California",
    imageUrl: "https://images.unsplash.com/photo-1551239262-61cf00f7f55d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=500",
    icon: "fas fa-sun",
    established: "1994",
  },
  {
    name: "Denali",
    description: "Denali is six million acres of wild land, bisected by one ribbon of road. Travelers along it see the relatively low-elevation taiga forest give way to high alpine tundra and snowy mountains, culminating in North America's tallest peak, 20,310' Denali.",
    state: "Alaska",
    imageUrl: "https://images.unsplash.com/photo-1535650463987-78e52bac9355?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=500",
    icon: "fas fa-mountain",
    established: "1917",
  },
  {
    name: "Everglades",
    description: "Everglades National Park protects an unparalleled landscape that provides important habitat for numerous rare and endangered species like the manatee, American crocodile, and the elusive Florida panther.",
    state: "Florida",
    imageUrl: "https://images.unsplash.com/photo-1564352969906-8b7f602570fa?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=500",
    icon: "fas fa-water",
    established: "1934",
  },
  {
    name: "Glacier",
    description: "Come and experience Glacier's pristine forests, alpine meadows, rugged mountains, and spectacular lakes. With over 700 miles of trails, Glacier is a hiker's paradise for adventurous visitors seeking wilderness and solitude.",
    state: "Montana",
    imageUrl: "https://images.unsplash.com/photo-1566145257777-2f75ad9b350f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=500",
    icon: "fas fa-icicles",
    established: "1910",
  },
  {
    name: "Grand Canyon",
    description: "Grand Canyon National Park, a World Heritage Site, encompasses 1,218,375 acres and lies on the Colorado Plateau in northwestern Arizona. The immense Grand Canyon is a mile deep, averages fifteen miles across, and stretches 277 river miles.",
    state: "Arizona",
    imageUrl: "https://images.unsplash.com/photo-1534251658754-28b0987326a9?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=500",
    icon: "fas fa-mountain",
    established: "1919",
  },
  {
    name: "Grand Teton",
    description: "Rising above a scene rich with extraordinary wildlife, pristine lakes, and alpine terrain, the Teton Range stands as a monument to the people who fought to protect it. These are mountains of the imagination, jagged peaks that inspired awe.",
    state: "Wyoming",
    imageUrl: "https://images.unsplash.com/photo-1533489129335-f71a8395157b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=500",
    icon: "fas fa-mountain",
    established: "1929",
  },
  {
    name: "Great Smoky Mountains",
    description: "Ridge upon ridge of forest stretching the border between North Carolina and Tennessee at Great Smoky Mountains National Park.",
    state: "Tennessee & North Carolina",
    imageUrl: "https://images.unsplash.com/photo-1578763397601-ad069af37f14?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=500",
    icon: "fas fa-leaf",
    established: "1934",
  },
  {
    name: "Joshua Tree",
    description: "Two distinct desert ecosystems, the Mojave and the Colorado, come together in Joshua Tree National Park. A fascinating variety of plants and animals make their homes in a land sculpted by strong winds and occasional torrents of rain.",
    state: "California",
    imageUrl: "https://images.unsplash.com/photo-1564507184343-942de0ba4906?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=500",
    icon: "fas fa-tree",
    established: "1994",
  },
  {
    name: "Olympic",
    description: "With its incredible range of precipitation and elevation, diversity is the hallmark of Olympic National Park. Encompassing nearly a million acres, the park protects a vast wilderness, thousands of years of human history, and several distinctly different ecosystems.",
    state: "Washington",
    imageUrl: "https://images.unsplash.com/photo-1575999635765-5abd35442988?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=500",
    icon: "fas fa-tree",
    established: "1938",
  },
  {
    name: "Rocky Mountain",
    description: "Rocky Mountain National Park's 415 square miles encompass and protect spectacular mountain environments. Trail Ridge Road – which crests at over 12,000 feet – lets you experience the park from subalpine forests to alpine tundra.",
    state: "Colorado",
    imageUrl: "https://images.unsplash.com/photo-1508517889477-17b12689e645?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=500",
    icon: "fas fa-mountain",
    established: "1915",
  },
  {
    name: "Shenandoah",
    description: "Shenandoah National Park extends along the Blue Ridge Mountains in Virginia. The Skyline Drive runs its length, and a vast network of trails includes a section of the long-distance Appalachian Trail.",
    state: "Virginia",
    imageUrl: "https://images.unsplash.com/photo-1541890289-bce5a9c8c5ff?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=500",
    icon: "fas fa-leaf",
    established: "1935",
  },
  {
    name: "Yellowstone",
    description: "Yellowstone National Park is a nearly 3,500-sq.-mile wilderness recreation area atop a volcanic hot spot. Mostly in Wyoming, the park spreads into parts of Montana and Idaho too. It features dramatic canyons, alpine rivers, lush forests, hot springs and gushing geysers, including its most famous, Old Faithful.",
    state: "Wyoming, Montana & Idaho",
    imageUrl: "https://images.unsplash.com/photo-1563299796-17e6c7862b36?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=500",
    icon: "fas fa-hot-tub",
    established: "1872",
  },
  {
    name: "Yosemite",
    description: "Yosemite National Park is in California's Sierra Nevada mountains. It's famed for its giant, ancient sequoia trees, and for Tunnel View, the iconic vista of towering Bridalveil Fall and the granite cliffs of El Capitan and Half Dome.",
    state: "California",
    imageUrl: "https://images.unsplash.com/photo-1562310503-a33c1757bd31?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=500",
    icon: "fas fa-mountain",
    established: "1890",
  },
  {
    name: "Zion",
    description: "Follow the paths where ancient native people and pioneers walked. Gaze up at massive sandstone cliffs of cream, pink, and red that soar into a brilliant blue sky. Experience wilderness in a narrow slot canyon.",
    state: "Utah",
    imageUrl: "https://images.unsplash.com/photo-1545133875-55b651cbf4aa?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=500",
    icon: "fas fa-mountain",
    established: "1919",
  }
];
